name = "Equilibrium_testing"
uid = "DEVELOP!-V37D-4759-3598-EQBALANCEMOD"
version = 37
copyright = "Ithilis - feel free to use this code, but ask permission first, and credit Equilibrium in your mod."
description = "This is the develop version of equilibrium. Use at your own risk!"
icon = "/mods/Equilibrium_balance_mod/Equilibrium_balance_mod.png"
author = "Ithilis"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
_faf_modname='equilibrium'
mountpoints = {
    ["."] = "/mods/equilibrium",
}